#!/usr/bin/env node
"use strict";

var assert = require('assert');
var fs = require('fs');


function jsonTypeof(x) {
	var t = typeof x;
	if (t === "number") {
		return t;
	} else if (t === "string") {
		return t;
	} else if (t === "boolean") {
		return t;
	} else {
		if (x === null) {
			return "null";
		} else {
			var y = Object.prototype.toString.call(x);
			if (y === "[object Array]") {
				return "array";
			} else if (y === "[object Object]") {
				return "object";
			}
		}
	}
	return undefined;
}


function validateType(path, x, type) {
	assert(jsonTypeof(x) === type, path + " not of type \"" + type + "\"");
}

function validateNumber(path, x) {
	validateType(path, x, "number");
}

function validateString(path, x) {
	validateType(path, x, "string");
}

function validateBoolean(path, x) {
	validateType(path, x, "boolean");
}

function validateNull(path, x) {
	validateType(path, x, "null");
}

function validateArray(path, x) {
	validateType(path, x, "array");
}

function validateObject(path, x) {
	validateType(path, x, "object");
}


function validateOnlyKeys(path, obj, keys) {
	for (var key in obj) {
		if (obj.hasOwnProperty(key))
			assert(keys.indexOf(key) !== -1, path + " contains unexpected key " + JSON.stringify(key));
	}
}

function validateRequiredKey(path, obj, key, valueValidator) {
	assert(obj.hasOwnProperty(key), path + " does not have key " + JSON.stringify(key));
	valueValidator(path + "[" + JSON.stringify(key) + "]", obj[key]);
}

function validateOptionalKey(path, obj, key, valueValidator) {
	if (obj.hasOwnProperty(key)) {
		valueValidator(path + "[" + JSON.stringify(key) + "]", obj[key]);
	}
}

function validateList(path, arr, valueValidator) {
	for (var i=0; i!=arr.length; ++i)
		valueValidator(path + "[" + i + "]", arr[i]);
}

function validateMap(path, obj, valueValidator) {
	for (var key in obj) {
		if (obj.hasOwnProperty(key)) {
			valueValidator(path + "[" + JSON.stringify(key) + "]", obj[key]);
		}
	}
}


function prevalidateApiDocument_schemas(path, x) {
	validateObject(path, x);
	validateOnlyKeys(path, x, ["string", "json"]);
	validateRequiredKey(path, x, "string", validateObject);
	validateRequiredKey(path, x, "json", validateObject);
}

function prevalidateApiDocument(path, x) {
	validateObject(path, x);
	validateOnlyKeys(path, x, ["sections", "methods", "schemas"]);
	validateRequiredKey(path, x, "sections", validateArray);
	validateRequiredKey(path, x, "methods", validateObject);
	validateRequiredKey(path, x, "schemas", prevalidateApiDocument_schemas);
}


function validateApiDocument_methods(path, x) {
	validateObject(path, x);
	validateMap(path, x, validateMethod);
}

function validateApiDocument_schemas(path, x) {
	validateObject(path, x);
	validateOnlyKeys(path, x, ["string", "json"]);
	validateRequiredKey(path, x, "string", function(p, y) { validateMap(p, y, validateStringSchema); });
	validateRequiredKey(path, x, "json", function(p, y) { validateMap(p, y, validateJsonSchema); });
}


function validateApiDocument(path, x) {
	validateObject(path, x);
	validateOnlyKeys(path, x, ["sections", "methods", "schemas"]);
	validateRequiredKey(path, x, "sections", validateSectionList);
	validateRequiredKey(path, x, "methods", validateApiDocument_methods);
	validateRequiredKey(path, x, "schemas", validateApiDocument_schemas);
}

function validateSectionList(path, x) {
	validateArray(path, x);
	validateList(path, x, validateSection);
}

function validateSection(path, x) {
	validateObject(path, x);
	validateOnlyKeys(path, x, ["name", "summary", "description", "methods"]);
	validateRequiredKey(path, x, "name", validateString);
	validateOptionalKey(path, x, "summary", validateString);
	validateOptionalKey(path, x, "description", validateString);
	validateRequiredKey(path, x, "methods", function(p, y) { validateList(p, y, function(q, z) {
		validateString(q, z);
		assert(top.methods.hasOwnProperty(z), q + " method reference " + JSON.stringify(z) + " not found");
	}); });
}

function validateMethod(path, x) {
	validateObject(path, x);
	validateOnlyKeys(path, x, ["method", "location", "location_type", "summary", "description", "method", "request", "response"]);
	validateRequiredKey(path, x, "method", validateString);
	validateRequiredKey(path, x, "location", validateString);
	validateRequiredKey(path, x, "location_type", validateString);
	validateOptionalKey(path, x, "summary", validateString);
	validateOptionalKey(path, x, "description", validateString);
	validateOptionalKey(path, x, "method", validateString);
	validateRequiredKey(path, x, "request", validateRequest);
	validateRequiredKey(path, x, "response", validateResponseList);
}

function validateRequest(path, x) {
	validateObject(path, x);
	validateOnlyKeys(path, x, ["path", "query", "header", "body"]);
	validateOptionalKey(path, x, "path", validateParameterList);
	validateOptionalKey(path, x, "query", validateParameterList);
	validateOptionalKey(path, x, "header", validateParameterList);
	validateOptionalKey(path, x, "body", validateBodyList);
}

function validateResponseList(path, x) {
	validateArray(path, x);
	validateList(path, x, validateResponse);
}

function validateResponse(path, x) {
	validateObject(path, x);
	validateOnlyKeys(path, x, ["name", "description", "statusCode", "statusMessage", "header", "body"]);
	validateOptionalKey(path, x, "name", validateString);
	validateOptionalKey(path, x, "description", validateString);
	validateRequiredKey(path, x, "statusCode", validateNumber);
	validateOptionalKey(path, x, "statusMessage", validateString);
	validateOptionalKey(path, x, "header", validateParameterList);
	validateOptionalKey(path, x, "body", validateBodyList);
}

function validateBodyList(path, x) {
	validateArray(path, x);
	validateList(path, x, validateBody);
}

function validateBody(path, x) {
	validateObject(path, x);
	validateRequiredKey(path, x, "type", validateString);
	if (x["type"] === "binary") {
		validateOnlyKeys(path, x, ["type"]);
	} else if (x["type"] === "form") {
		validateOnlyKeys(path, x, ["type", "contentType", "parameters"]);
		validateOptionalKey(path, x, "contentType", validateString);
		validateRequiredKey(path, x, "parameters", validateParameterList);
	} else if (x["type"] === "json") {
		validateOnlyKeys(path, x, ["type", "contentType", "schema"]);
		validateOptionalKey(path, x, "contentType", validateString);
		validateRequiredKey(path, x, "schema", validateJsonSchema);
	} else {
		assert(false, path + " has invalid type " + JSON.stringify(x["type"]));
	}		
}

function validateParameterList(path, x) {
	validateArray(path, x);
	validateList(path, x, validateParameter);
}

function validateParameter(path, x) {
	validateObject(path, x);
	validateOnlyKeys(path, x, ["name", "description", "frequency", "value"]);
	validateRequiredKey(path, x, "name", validateStringSchema);
	validateOptionalKey(path, x, "description", validateString);
	validateRequiredKey(path, x, "frequency", validateString);
	validateRequiredKey(path, x, "value", validateStringSchema);
}

function validateStringSchema(path, x) {
	var t = jsonTypeof(x);
	if (t === "string") {
		;
	} else if (t === "object") {
		if (x.hasOwnProperty("ref")) {
			validateOnlyKeys(path, x, ["ref"]);
			validateRequiredKey(path, x, "ref", validateString);
			assert(top.schemas.string.hasOwnProperty(x["ref"]), path + " string schema reference " + JSON.stringify(x["ref"]) + " not found");
		} else {
			validateOnlyKeys(path, x, ["criteria", "examples"]);
			validateOptionalKey(path, x, "criteria", function(p, y) { validateList(p, y, validateString); });
			validateOptionalKey(path, x, "examples", function(p, y) { validateList(p, y, validateString); });
		}
	} else {
		assert(false, path + " is of invalid type " + JSON.stringify(t));
	}
}

function validateJsonSchema(path, x) {
	validateObject(path, x);
	if (x.hasOwnProperty("ref")) {
		validateOnlyKeys(path, x, ["ref"]);
		validateRequiredKey(path, x, "ref", validateString);
		assert(top.schemas.json.hasOwnProperty(x["ref"]), path + " json schema reference " + JSON.stringify(x["ref"]) + " not found");
	} else {
		validateRequiredKey(path, x, "type", validateString);
		if (x["type"] === "null") {
			validateOnlyKeys(path, x, ["type"]);
		} else if (x["type"] === "boolean") {
			validateOnlyKeys(path, x, ["type"]);
		} else if (x["type"] === "number") {
			validateOnlyKeys(path, x, ["type", "criteria", "examples"]);
			validateOptionalKey(path, x, "criteria", function(p, y) { validateList(p, y, validateString); });
			validateOptionalKey(path, x, "examples", function(p, y) { validateList(p, y, validateString); });
		} else if (x["type"] === "string") {
			validateOnlyKeys(path, x, ["type", "format"]);
			validateOptionalKey(path, x, "format", validateStringSchema);
		} else if (x["type"] === "array") {
			validateOnlyKeys(path, x, ["type", "criteria", "examples", "items"]);
			validateOptionalKey(path, x, "criteria", function(p, y) { validateList(p, y, validateString); });
			validateOptionalKey(path, x, "examples", function(p, y) { validateList(p, y, validateString); });
			validateRequiredKey(path, x, "items", validateJsonItemList);
		} else if (x["type"] === "object") {
			validateOnlyKeys(path, x, ["type", "criteria", "examples", "properties"]);
			validateOptionalKey(path, x, "criteria", function(p, y) { validateList(p, y, validateString); });
			validateOptionalKey(path, x, "examples", function(p, y) { validateList(p, y, validateString); });
			validateRequiredKey(path, x, "properties", validateJsonPropertyList);
		} else {
			assert(false, path + "[\"type\"] has an invalid value " + JSON.stringify(x["type"]));
		}
	}
	return false;
}

function validateJsonItemList(path, x) {
	validateArray(path, x);
	validateList(path, x, validateJsonItem);
}

function validateJsonItem(path, x) {
	validateObject(path, x);
	validateOnlyKeys(path, x, ["index", "description", "value"]);
	validateRequiredKey(path, x, "index", validateString);
	validateOptionalKey(path, x, "description", validateString);
	validateRequiredKey(path, x, "value", validateJsonSchema);
}

function validateJsonPropertyList(path, x) {
	validateArray(path, x);
	validateList(path, x, validateJsonProperty);
}

function validateJsonProperty(path, x) {
	validateObject(path, x);
	validateOnlyKeys(path, x, ["key", "description", "frequency", "value"]);
	validateRequiredKey(path, x, "key", validateStringSchema);
	validateOptionalKey(path, x, "description", validateString);
	validateRequiredKey(path, x, "frequency", validateString);
	validateRequiredKey(path, x, "value", validateJsonSchema);
}



if(process.argv.length < 3) {
	console.error("No filename specified.");
	process.exit(1);	
}

var fn = process.argv[2];
var body = null;
try {
	body = fs.readFileSync(fn, 'utf8');	
}
catch(e) {
	console.error("Couldn't read: "+e);
	process.exit(1);
}

var top = null;
try {
	top = JSON.parse(body);
}
catch(e) {
	console.error("Couldn't parse: "+e);
	process.exit(1);
}

try {
	prevalidateApiDocument("document", top);
	validateApiDocument("document", top);
}
catch(e) {
	if (!(e instanceof assert.AssertionError))
		throw e;
	console.error(e.message);
}
