#!/usr/bin/env node
"use strict";

var fs = require('fs');
var Hapi = require('./hapi.js');

if(process.argv.length < 3) {
	console.error("No filename specified.");
	process.exit(1);	
}

var fn = process.argv[2];
var body = null;
try {
	body = fs.readFileSync(fn, 'utf8');	
}
catch(e) {
	console.error("Couldn't read: "+e);
	process.exit(1);
}

var httpapiSpec = null;
try {
	httpapiSpec = JSON.parse(body);
}
catch(e) {
	console.error("Couldn't JSON parse: "+e);
	process.exit(1);
}

try {
	Hapi.validate(httpapiSpec);
}
catch(e) {
	if (!(e instanceof Hapi.ParseError))
		throw e;
	console.error(e.message);
	process.exit(1);
}

var httpapiSpecParsed = null;
try {
	httpapiSpecParsed = Hapi.parse(httpapiSpec);
}
catch(e) {
	if (!(e instanceof Hapi.ParseError))
		throw e;
	console.error(e.message);
	process.exit(1);
}

process.exit(0);
